init_learning: False

environment: 'SuperMarioBros-1-1-v1'
actions: [['right'], ['right', 'A']] # 'SIMPLE_MOVEMENT'



state_height: 84
state_width: 84
state_channel: 4
state_skip: 4

episodes: 30000
batch_size: 32
save_interval: 100
memory_length: 5e4

##
gamma: 0.9
lr: 0.00025
optimizer: Adam
loss_fn: SmoothL1Loss
burnin: 1e4
learn_every: 3
sync_every: 1e4


## 
exploration_rate: 1
exploration_rate_decay: 0.99999975
exploration_rate_min: 0.1